{% set name = "presto-python-client" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/presto-python-client-{{ version }}.tar.gz
  sha256: 260249efefbcf56f407f93d39d92fb9963164ca3d7abffa4493fd127346d2732

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - click
    - python >=3.5
    - requests
    - six

test:
  imports:
    - prestodb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/prestodb/presto-python-client
  summary: Client for the Presto distributed SQL Engine
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/prestodb/presto-python-client
  doc_url: https://github.com/prestodb/presto-python-client

extra:
  recipe-maintainers:
    - xylar
